# Generated by Django 4.2.7 on 2023-11-18 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('call_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={
                'verbose_name': 'оценку',
                'verbose_name_plural': 'оценки',
            },
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={
                'verbose_name': 'сотрудника',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=8,
                        message='Пароль должен содержать не менее 8 символов.',
                    ),
                    django.core.validators.RegexValidator(
                        message='Пароль должен содержать хотя бы 1 заглавную букву.',
                        regex='[A-Z]',
                    ),
                ],
                verbose_name='пароль',
            ),
        ),
    ]
