# Generated by Django 4.2.7 on 2023-11-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'call_center',
            '0002_alter_category_options_alter_mark_options_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(
                max_length=70, unique=True, verbose_name='название'
            ),
        ),
    ]
