# Generated by Django 4.2.7 on 2023-11-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('call_center', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=70, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id_category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='question',
                to='call_center.category',
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='id_worker',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='question',
                to='call_center.worker',
            ),
        ),
    ]
