# Generated by Django 4.2.7 on 2023-11-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'call_center',
            '0004_alter_category_name_alter_question_id_category_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(
                max_length=70, unique=True, verbose_name='название'
            ),
        ),
        migrations.AlterField(
            model_name='worker',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
