# Generated by Django 4.2.7 on 2023-11-18 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('call_center', '0005_alter_category_name_alter_worker_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='worker',
            managers=[],
        ),
    ]
