# Generated by Django 4.2.7 on 2023-11-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'call_center',
            '0007_alter_worker_managers_question_id_user_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id_user',
            field=models.TextField(null=True),
        ),
    ]
