# Generated by Django 4.2.7 on 2023-11-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='this_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.TextField(default='LPXUbOa8fjRUOKws'),
        ),
    ]
