# Generated by Django 4.2.7 on 2023-11-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('homepage', '0002_user_this_worker_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='worker_login',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='worker_password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.TextField(default='tDMBTzjkoPMrCWbF'),
        ),
    ]
